### ISSUE TITLE
Which is the meaning of the numbers?

### ISSUE THREAD

**Issue by Pablohn26** [ivmartel/dcmbench#1]
I have tried this benchmark with [the online webpage](http://ivmartel.github.io/dcmbench/)

The results are the following:

dcmjs | dicomParser | dwv | daikon
-- | -- | -- | --
144 | 14224 | 6136 | 4983

which is the meaning of the numbers? high is better?

**Comment by ivmartel** [comment]
These are the number of operations per second output by the benchmark library ([bestiejs/benchmark.js](https://github.com/bestiejs/benchmark.js)). There is more detail in the log. And yes, high is better.

Be aware that the comparison is **NOT fair** since the different parsers do not do the same thing, some will interpret the data and some wont (for ex `dicomParser`). This is just an indicative value.
